### PR TITLE
Add VacFind to the list of national projects

### PR DESCRIPTION
**Pull request by MoralCode**

### CODE REVIEW

**Comment by Mr0grog** [comment]
Hi @MoralCode! I’ll merge this, but I’m wondering if you’ve talked with the folks at https://findyourvaccine.org. They are doing very similar work to what it sounds like you are aimed at doing, and actively convene and support folks from many of the other community groups (e.g. VaccinateNJ, Vaccine List NYC, etc.). If not, you should definitely get in touch.

**Comment by MoralCode** [comment]
> I’m wondering if you’ve talked with the folks at https://findyourvaccine.org. They are doing very similar work to what it sounds like you are aimed at doing, and actively convene and support folks from many of the other community groups (e.g. VaccinateNJ, Vaccine List NYC, etc.). If not, you should definitely get in touch.

I have not previously reached out to them, however i just sent them an email. and invited them to join our discord community (https://discord.vacfind.org) so we can build a community with creators and devs from many different projects and collaborate. If anyone from the US Digital response is interested, feel free to join as well!

**Comment by MoralCode** [comment]
@Mr0grog apologies for the delayed update but i wanted to let you know that our project domain (vacfind) is no longer controlled by us and to my knowledge now contains NSFW content put there by its current owner. if this list is still used or still being maintained it may be important to remove this.

**Comment by Mr0grog** [comment]
Thanks for the heads-up! Do you know the last date it was still good? I'll see about replacing it with a web.archive.org link and adding a "retired" note or something.

That said, this repo isn't really still being maintained — I should see if I have permissions to archive it. (And probably give every link the same web.archive.org treatment.)

**Comment by MoralCode** [comment]
I got a notice on 12/27/2021 informing us we had 30 days before the domain expired, so that was basically the end of the time window where we had control over it. although towards the end of our project there weren't many changes to the site anyways. The site still seems to be up on github pages too, even though it no longer has the domain (https://vacfind.github.io/VacFind-site/). Even that GH pages site probably isnt worth keeping around for too long just to save github some hosting resources, but ill probably procrastinate doing anything with that for a long time so its probably reasonably archived.

**Comment by Mr0grog** [comment]
Updated. Thanks again!

**Pull request merged**
